name: CI/CD con Serveo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install
        # Paso 4: Definir etiqueta semántica (Versión de git)
      - name: Definir etiqueta semántica
        id: version_tag
        run: |
        # Obtener la versión semántica desde el último tag en Git
        VERSION=$(git describe --tags --abbrev=0)
        # Guardar la etiqueta en una variable de entorno
        echo "TAG=${VERSION}" >> $GITHUB_ENV
      - name: Ejecutar tests
        run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Autenticarse en Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}"/api-basica:${{ env.TAG }} .

      - name: Subir imagen a Docker Hub
        run: docker push "${{ secrets.DOCKER_USERNAME }}"/api-basica:${{ env.TAG }} .

      - name: Hacer deploy a WSL vía Serveo con contraseña
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}"/api-basica
            docker stop api-basica || true
            docker rm api-basica || true
            docker run -d --name api-basica -p 3000:3000 "${{ secrets.DOCKER_USERNAME }}"/api-basica